const actions = {
  INIT_DATA: 'ECOMMERCE_INIT_DATA',
  INIT_DATA_SAGA: 'ECOMMERCE_INIT_DATA_SAGA',

  DELETE_PRODUCT: 'ECOMMERCE_DELETE_PRODUCT',
  DELETE_PRODUCT_SUCCESS: 'ECOMMERCE_DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILURE: 'ECOMMERCE_DELETE_PRODUCT_FAILURE',
  CREATE_PRODUCT: 'ECOMMERCE_CREATE_PRODUCT',
  CREATE_PRODUCT_SUCCESS: 'ECOMMERCE_CREATE_PRODUCT_SUCCESS',
  CREATE_PRODUCT_FAILURE: 'ECOMMERCE_CREATE_PRODUCT_FAILURE',

  CREATE_CATEGORY: 'ECOMMERCE_CREATE_CATEGORY',
  CREATE_CATEGORY_SUCCESS: 'ECOMMERCE_CREATE_CATEGORY_SUCCESS',
  CREATE_CATEGORY_FAILURE: 'ECOMMERCE_CREATE_CATEGORY_FAILURE',
  DELETE_CATEGORY: 'ECOMMERCE_DELETE_CATEGORY',
  DELETE_CATEGORY_SUCCESS: 'ECOMMERCE_DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILURE: 'ECOMMERCE_DELETE_CATEGORY_FAILURE',
  FETCH_CATEGORIES: 'ECOMMERCE_FETCH_CATEGORIES',
  FETCH_CATEGORIES_SUCCESS: 'ECOMMERCE_FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILURE: 'ECOMMERCE_FETCH_CATEGORIES_FAILURE',

  // Existing actions
  initData: () => ({ type: actions.INIT_DATA_SAGA }),
  createProduct: (productData, navigate) => ({
    type: actions.CREATE_PRODUCT,
    payload: {
      productData,
      navigate,
    },
  }),
  // Add new action creators for category creation and fetching
  createCategory: (categoryData, navigate) => ({
    type: actions.CREATE_CATEGORY,
    payload: {
      categoryData,
      navigate,
    },
  }),
  fetchCategories: () => ({
    type: actions.FETCH_CATEGORIES,
  }),
};
export default actions;
